config/routes.rb
Pieceofthefuture::Application.routes.draw do      
  devise_for :users
  get '/institutions/search' => 'institutions#search'
  post '/institutions/get_institution'
  post '/classrooms/get_classroom'
  resources :institutions
  resources :classrooms

  match '/donations/receipt/:id' => 'donations#receipt', :as => :receipt
  match '/donations/send_information/:id' => 'donations#send_information', :as => :send_information
  match 'donations/update_classroom_select/:id' => 'donations#update_classroom_select'
  resources :donations
  post '/donate/send_email'
  match 'faq' => 'high_voltage/pages#show', :id => 'faq'
  match 'about_tff' => 'high_voltage/pages#show', :id => 'about_tff'
  match 'terms_and_conditions' => 'high_voltage/pages#show', :id => 'terms'
  match 'prizes' => 'high_voltage/pages#show', :id => 'prizes'
  match 'contributors' => 'contributors#index'
  match 'contact' => 'contact_mailer#index'
  post 'contact_mailer/send_email'

  root :to => 'home#index'

end

app/models/institution.rb
# == Schema Information
# Schema version: 20110410031628
#
# Table name: institutions
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  school_site   :string(255)
#  contact_name  :string(255)
#  contact_email :string(255)
#  contact_title :string(255)
#  street_one    :string(255)
#  street_two    :string(255)
#  city          :string(255)
#  state         :string(255)
#  postal_code   :string(255)
#  phone         :string(255)
#  wish_list     :text
#  created_at    :datetime
#  updated_at    :datetime
#

class Institution < ActiveRecord::Base
  has_many :classrooms
  has_many :donations
  
  validates :name, :presence => true, :uniqueness => true
  validates :contact_name, :presence => true
  validates :contact_email, :presence => true, :confirmation => true
  validates :street_one, :city, :state, :postal_code, :phone, :presence => true

  attr_accessible :name, :school_site, :contact_name, :contact_email, :contact_title,
    :street_one, :street_two, :city, :state, :postal_code, :phone, :wish_list    
    
  def self.search(search)  
    if search  
      where('name ILIKE ?', "%#{search}%")  
    else  
      scoped  
    end  
  end 
  
  def classroom_ordered
    self.classrooms.order(:name)
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :destroy]
  # GET /institutions
  # GET /institutions.xml
  def index        
    @institutions = Institution.search(params[:search]).order(:name).paginate(:page => params[:institutions_page], :per_page => 20)          
    @classrooms = Classroom.search(params[:search]).order(:name).paginate(:page => params[:classroom_page], :per_page => 20)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @institutions }
    end
  end
  
  def search
    @institution_search = Institution.search(params[:search])
    @institutions = @institution_search.order(:name).paginate(:page => params[:institutions_page], :per_page => 30)
  end

  # GET /institutions/1
  # GET /institutions/1.xml
  def show
    @institution = Institution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @institution }
    end
  end

  # GET /institutions/new
  # GET /institutions/new.xml
  def new
    @institution = Institution.new
    @states = Decoder::Countries[:US].states.invert

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @institution }
    end
  end

  def get_institution
    session[:institution_id] = params[:institution_id]
    redirect_to terms_and_conditions_path
  end

  # GET /institutions/1/edit
  def edit
    @institution = Institution.find(params[:id])
    @states = Decoder::Countries[:US].states.invert
  end

  # POST /institutions
  # POST /institutions.xml
  def create
    @institution = Institution.new(params[:institution])
    @states = Decoder::Countries[:US].states.invert

    respond_to do |format|
      if @institution.save
        format.html { redirect_to(@institution, :notice => 'Successfully created an Institution. GOOD LUCK!') }
        format.xml  { render :xml => @institution, :status => :created, :location => @institution }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @institution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /institutions/1
  # PUT /institutions/1.xml
  def update
    @institution = Institution.find(params[:id])

    respond_to do |format|
      if @institution.update_attributes(params[:institution])
        format.html { redirect_to(@institution, :notice => 'Institution was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @institution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.xml
  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to(institutions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_classrooms.haml
%h2 Classrooms
%table.plain{:width => '100%'}
  %thead
    %tr
      %th{ :scope => 'col' } Name (click to view classroom)
      %th Institution
  %tbody
    - unless @classrooms.nil?
      - @classrooms.each do |classroom|
        %tr{:style => 'vertical-align:text-top;'}
          %td.classroom_name
            = link_to "#{classroom.teacher_with_class}", classroom
          %td= link_to "#{classroom.institution.name}", classroom.institution

app/views/institutions/_form.html.haml
= form_for(@institution) do |f|
  = f.error_messages
  %table
    %tr
      %td.label
        = f.label :name, 'Institution Name:'
      %td
        = f.text_field :name
        %span.required *
        .form_input_notes Please enter name of educational institution
    %tr
      %td.label
        = f.label :school_site, 'Institution Web Address:'
        http://
      %td
        = f.text_field :school_site
    %tr
      %td.label
        = f.label :contact_name, 'Contact Name:'
      %td
        = f.text_field :contact_name
        %span.required *
        .form_input_notes Please enter name of school contact
    %tr
      %td.label
        = f.label :contact_email, 'Contact Email:'
      %td
        = f.email_field :contact_email
        %span.required *
        .form_input_notes Please enter email for school contact
    %tr
      %td.label
        = f.label :contact_email_confirmation, 'Confirm Email:'
      %td
        = f.email_field :contact_email_confirmation
        %span.required *
        .form_input_notes Please confirm email
    %tr
      %td.label
        = f.label :contact_title, 'Contact Title:'
      %td
        = f.text_field :contact_title
        .form_input_notes Please enter title of school contact
    %tr
      %td.label
        = f.label :street_one, 'Address 1:'
      %td
        = f.text_field :street_one
        %span.required *
        .form_input_notes Please enter street address for school
    %tr
      %td.label
        = f.label :street_two, 'Address 2:'
      %td
        = f.text_field :street_two
    %tr
      %td.label
        = f.label :city, 'City:'
      %td
        = f.text_field :city
        %span.required *
        .form_input_notes Please enter school's city
    %tr
      %td.label
        = f.label :state, 'State:'
      %td
        = f.select :state, @states
        %span.required *
    %tr
      %td.label
        = f.label :postal_code, 'Zip Code:'
      %td
        = f.text_field :postal_code
        %span.required *
        .form_input_notes Please enter zip code of school
    %tr
      %td.label
        = f.label :phone, 'Phone Number:'
      %td
        = f.text_field :phone
        %span.required *
        .form_input_notes Please enter contact phone number
    %tr
      %td.label{:style => 'vertical-align:top;'}
        = f.label :wish_list, 'Wish List:'
      %td
        = f.text_area :wish_list
    %tr
      %td &nbsp;
      %td
        = f.submit :class => "styled_button blue"
        = link_to 'Back', institutions_path, :class => 'grey styled_button'

app/views/institutions/_institutions.haml
%h2 Institutions
%table.plain{:width => '100%'}
  %thead
    %tr
      %th{ :scope => 'col' } Name (click to see classrooms)
      %th
  %tbody
    - unless @institutions.nil?
      - @institutions.each do |institution|
        %tr{:style => 'vertical-align:text-top;'}
          %td.institution_name
            = link_to "#{institution.name}", 'javascript:void(0);'
            - institution.classrooms.each do |classroom|
              %ul.classrooms
                %li
                  &#187;
                  = link_to "#{classroom.teacher_with_class}", classroom, :title => "View #{classroom.name}"
          %td
            = link_to image_tag('/images/notjustagrid/icons/icon-view.png', :alt => 'Show School', :title => 'Show School') + ' View Institution', institution
            /
              = link_to image_tag('/images/notjustagrid/icons/icon-edit.png', :alt => 'Edit School', :title => 'Edit School'), edit_institution_path(institution)
              = link_to image_tag('/images/notjustagrid/icons/icon-delete.png', :alt => 'Delete School', :title => 'Delete School'), institution, :confirm => 'Are you sure?', :method => :delete

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render 'form' %>

app/views/institutions/index.html.haml
- title "Piece of the Future => Educational Institutions"
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_lightpurp.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_04.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_title_classrooms.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "890"}
        %tr
          %td{:align => "left", :style => "padding-left: 10px;", :valign => "top", :width => "610"}          
            = form_tag institutions_path, :method => :get, :id => "search" do
              %p 
                Search Institutions or Classrooms:
                = text_field_tag :search, params[:search]
                = submit_tag 'Search', :name => nil
            #institutions
              = render 'institutions'             
            - unless @institutions.nil?
              = will_paginate @institutions, :param_name => :institutions_page
            %br
            %br
            #classrooms= render 'classrooms'
            - unless @classrooms.nil?
              = will_paginate @classrooms, :param_name => :classrooms_page
            %br
            %br
            = link_to 'Create Institution', new_institution_path, :class => 'blue styled_button', :style => 'color:#fff;'
            = link_to 'Create Classroom', new_classroom_path, :class => 'blue styled_button', :style => 'color:#fff;'
          %td{:align => "right", :valign => "top", :width => "280", :style => 'padding-top:30px;'}
            %img{:height => "400", :src => "/images/sidebanners_classrooms.png", :width => "270"}/
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_kids.png", :width => "1000"}/

app/views/institutions/index.js.erb
$('#institutions').html('<%= escape_javascript(render("institutions")) %>'); 

app/views/institutions/new.html.haml
- title "Piece of the Future => New Institutions"
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_lightpurp.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_04.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_subtitle_newinstitution.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      = render 'form'
  /
    %p
      = link_to 'Back', institutions_path, :class => 'grey styled_button'
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_kids.png", :width => "1000"}/

app/views/institutions/search.haml
- title "Piece of the Future => Search Results"
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_lightpurp.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_04.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_title_classrooms.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "890"}
        %tr
          %td{:align => "left", :style => "padding-left: 10px;", :valign => "top", :width => "610"}          
            = form_for @institution_search, :url => {:action => 'search'} do |f|
              %p 
                Search Institutions:
                = f.text_field :name_or_classrooms_class_name_or_classrooms_teacher_contains
                /
                  %p
                    Search Classrooms:
                    = f.text_field :classrooms_class_name_contains
                = f.submit 'Search'
            #institutions
              %table.plain{:width => '100%'}
                %thead
                  %tr
                    %th{ :scope => 'col' } Name (click to see classrooms)
                    %th
                %tbody
                  - unless @institutions.nil?
                    - @institutions.each do |institution|
                      %tr{:style => 'vertical-align:text-top;'}
                        %td.institution_name
                          - if institution.name.nil?
                          = link_to "#{institution.name}", 'javascript:void();'
            - unless @institutions.nil?
              = will_paginate @institutions, :param_name => :institutions_page
            %br
            %br
            = link_to 'Create Institution', new_institution_path, :class => 'blue styled_button', :style => 'color:#fff;'
            = link_to 'Create Classroom', new_classroom_path, :class => 'blue styled_button', :style => 'color:#fff;'
          %td{:align => "right", :valign => "top", :width => "280", :style => 'padding-top:30px;'}
            %img{:height => "400", :src => "/images/sidebanners_classrooms.png", :width => "270"}/
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_kids.png", :width => "1000"}/

app/views/institutions/show.html.haml
- title "Piece of the Future => #{@institution.name}"
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_lightpurp.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_04.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_subtitle_newinstitution.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      %h4.resource_name= @institution.name
      = form_tag '/institutions/get_institution' do
        = hidden_field_tag :institution_id, "#{@institution.id}"
        = submit_tag 'Donate to this Institution'
      %p.clear
        %b Contact name:
        = @institution.contact_name
      %p
        %b Contact email:
        = @institution.contact_email
      %p
        %b Contact title:
        = @institution.contact_title
      %p
        %b Phone:
        = @institution.phone
      %p
        %b Wish List:
        = @institution.wish_list
      \#{link_to 'Back to Institutions', institutions_path, :class => 'blue styled_button', :style => 'color:white;'}
      = link_to 'New Classroom Page', new_classroom_path, :class => 'blue styled_button', :style => 'color:white;'
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_kids.png", :width => "1000"}/