config/routes.rb
Pieceofthefuture::Application.routes.draw do      
  devise_for :users
  get '/institutions/search' => 'institutions#search'
  post '/institutions/get_institution'
  post '/classrooms/get_classroom'
  resources :institutions
  resources :classrooms

  match '/donations/receipt/:id' => 'donations#receipt', :as => :receipt
  match '/donations/send_information/:id' => 'donations#send_information', :as => :send_information
  match 'donations/update_classroom_select/:id' => 'donations#update_classroom_select'
  resources :donations
  post '/donate/send_email'
  match 'faq' => 'high_voltage/pages#show', :id => 'faq'
  match 'about_tff' => 'high_voltage/pages#show', :id => 'about_tff'
  match 'terms_and_conditions' => 'high_voltage/pages#show', :id => 'terms'
  match 'prizes' => 'high_voltage/pages#show', :id => 'prizes'
  match 'contributors' => 'contributors#index'
  match 'contact' => 'contact_mailer#index'
  post 'contact_mailer/send_email'

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.haml
- title 'Piece of the Future => Home'
#grid
  = link_to '', 'http://noellebowen.bodybyvi.com', :id => 'noelle_bowen_1', :class => 'box_link_left', :target => '_blank'
  .tooltip.portrait
    #noelle_bowen_1_img.ad_img
    %br
    %span.label Buyer:
    Noelle Bowen
    %br
    %span.label Email:
    = mail_to 'noelle.bowen@hotmail.com'
    %br
    %span.label School:
    = link_to 'Sandalwood', institution_path(3)
    %br
    %span.label Classroom:
    = link_to "Noelle Bowen", classroom_path(3)
    %br
    %span.label Donated:
    $5.00
    %br
    %span.label Website:
    = link_to 'noellebowen.bodybyvi.com', 'http://noellebowen.bodybyvi.com', :target => '_blank'
  = link_to '', 'http://www.hogan.bodybyvi.com/', :id => 'joshua_hogan_1', :class => 'box_link_left', :target => '_blank'
  .tooltip.portrait
    #joshua_hogan_1_img.ad_img
    %br
    %span.label Buyer:
    Joshua Hogan
    %br
    %span.label Email:
    = mail_to 'hoganj3@duvalschool.org'
    %br
    %span.label School:
    = link_to 'Highlands', institution_path(1)
    %br
    %span.label Classroom:
    = link_to "Hogan's Heroes", classroom_path(1)
    %br
    %span.label Donated:
    $10.00
    %br
    %span.label Website:
    = link_to 'http://www.hogan.bodybyvi.com/', 'http://www.hogan.bodybyvi.com/', :target => '_blank'
  = link_to '', 'http://www.google.com', :id => 'joshua_hogan_2', :class => 'box_link_left', :target => '_blank'
  .tooltip.portrait
    #joshua_hogan_2_img.ad_img
    %br
    %span.label Buyer:
    Joshua Hogan
    %br
    %span.label Email:
    = mail_to 'joshua@tomorrowsfuturefoundation.org'
    %br
    %span.label School:
    = link_to 'Highlands', institution_path(1)
    %br
    %span.label Classroom:
    = link_to 'Carter - Paula Carter', classroom_path(2)
    %br
    %span.label Donated:
    $20.00
    %br
    %span.label Website:
    = link_to 'www.google.com', 'http://www.google.com', :target => '_blank'
  = link_to '', 'http://www.tomorrowsfuturefoundation.org', :id => 'robinsons_1', :class => 'box_link_left', :target => '_blank'
  .tooltip.portrait
    #robinsons_1_img.ad_img
    %br
    %span.label Buyer:
    The Robinsons
    %br
    %span.label School:
    = link_to 'Sandalwood', institution_path(3)
    %br
    %span.label Classroom:
    = link_to 'Noelle Bowen', classroom_path(3)
    %br
    %span.label Donated:
    $580.00
    %br
    %span.label Website:
    = link_to 'www.tomorrowsfuturefoundation.org', 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
  = link_to '', 'http://broadmac.net', :id => 'evan_machnic_1', :class => 'box_link_left', :target => '_blank'
  .tooltip.portrait
    #evan_machnic_1_img.ad_img
    %br
    %span.label Buyer:
    Evan Machnic
    %br
    %span.label School:
    = link_to 'Allen D. Nease High School', institution_path(4)
    %br
    %span.label Classroom:
    = link_to 'Learning Strategies - Jan Carlyle', classroom_path(6)
    %br
    %span.label Donated:
    $5.00
    %br
    %span.label Website:
    = link_to 'broadmac.net', 'http://broadmac.net', :target => '_blank'
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_hand.png", :width => "1000"}/