config/routes.rb
Pieceofthefuture::Application.routes.draw do      
  devise_for :users
  get '/institutions/search' => 'institutions#search'
  post '/institutions/get_institution'
  post '/classrooms/get_classroom'
  resources :institutions
  resources :classrooms

  match '/donations/receipt/:id' => 'donations#receipt', :as => :receipt
  match '/donations/send_information/:id' => 'donations#send_information', :as => :send_information
  match 'donations/update_classroom_select/:id' => 'donations#update_classroom_select'
  resources :donations
  post '/donate/send_email'
  match 'faq' => 'high_voltage/pages#show', :id => 'faq'
  match 'about_tff' => 'high_voltage/pages#show', :id => 'about_tff'
  match 'terms_and_conditions' => 'high_voltage/pages#show', :id => 'terms'
  match 'prizes' => 'high_voltage/pages#show', :id => 'prizes'
  match 'contributors' => 'contributors#index'
  match 'contact' => 'contact_mailer#index'
  post 'contact_mailer/send_email'

  root :to => 'home#index'

end

app/views/pages/about_tff.haml
- title "Piece of the Future => About TFF"
- content_for :head do
  :javascript
    
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_orange.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_09.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_title_abouttff.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "890"}
        %tr
          %td{:align => "left", :valign => "top"}
            %img{:height => "43", :src => "/images/thecontent_about_ttf.png", :width => "431"}/
          %td{:align => "right", :rowspan => "2", :valign => "top", :width => "445"}
            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "416"}
              %tr
                %td{:width => "208"} &nbsp;
                %td{:width => "208"}
                  %img{:height => "105", :src => "/images/tff_imgs01.png", :width => "208"}/
              %tr
                %td
                  %img#img2{:border => "0", :height => "105", :name => "img2", :onmouseout => "MM_swapImgRestore()", :onmouseover => "MM_swapImage('img2','','/images/tff_imgs02.png',1)", :src => "/images/tff_imgs02_bw.png", :width => "208"}/
                %td
                  %img#img3{:border => "0", :height => "105", :name => "img3", :onmouseout => "MM_swapImgRestore()", :onmouseover => "MM_swapImage('img3','','/images/tff_imgs03.png',1)", :src => "/images/tff_imgs03_bw.png", :width => "208"}/
              %tr
                %td
                  %img#img4{:border => "0", :height => "105", :name => "img4", :onmouseout => "MM_swapImgRestore()", :onmouseover => "MM_swapImage('img4','','/images/tff_imgs04.png',1)", :src => "/images/tff_imgs04_bw.png", :width => "208"}/
                %td
                  %img#img5{:border => "0", :height => "105", :name => "img5", :onmouseout => "MM_swapImgRestore()", :onmouseover => "MM_swapImage('img5','','/images/tff_imgs05.png',1)", :src => "/images/tff_imgs05_bw.png", :width => "208"}/
              %tr
                %td
                  %img#img6{:border => "0", :height => "105", :name => "img6", :onmouseout => "MM_swapImgRestore()", :onmouseover => "MM_swapImage('img6','','/images/tff_imgs06.png',1)", :src => "/images/tff_imgs06_bw.png", :width => "208"}/
                %td &nbsp;
        %tr
          %td{:align => "left", :style => "padding-left: 48px; padding-right: 18px;", :valign => "top"}
            %p
              = link_to "Tomorrow's Future Foundation", 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
              is a 501(c)3 non-profit organization, that is exploring creative ways to
              counterbalance the unfortunate funding problems that are hindering the educational process.
            %p
              No one can deny that the public school systems in Florida are in dire financial straits because of the
              budget cuts. Throughout the nation, educational systems are continuously being asked to tighten their
              belts. That equates to a decrease in funding of $1000 per student next year and a sharp decrease in
              necessary supplies for schools, teachers and ultimately the students.
            %p
              Funding is important to the success of the educational systems, academic achievement and the retention
              of quality educators. Educators are the driving force of the school system and are constantly being
              asked to do more with less.
            %blockquote{:style => 'padding-left:30px;'}
              %p
                &#187; Your donation provides a school with materials, teachers with resources and students with the
                opportunity to succeed.
              %p
                &#187; It promotes you as a business with an investment in the future and lasting ties to the community.
              %p
                &#187; Your generosity creates a better educated community, which translates into smarter employees and
                consumers.
  %tr{:style => 'text-align:left;'}
    %td{:style => 'padding:0 10px 0 48px;'}
      %p
        %strong Your Donations at Work
      %blockquote{:style => 'padding-left:30px;'}
        %p
          &#187; $20 will supply 145 students with paper, pencils and erasers.
        %p
          &#187; $25 buys a School-Pak which includes: 1 box of crayons (24ct), erasers, 2 pocketed folders, 14 oz.
          glue, ruler, scissors, 1 set washable markers, 4 notebooks (70pg), pencils, 1 set of colored pencils,
          paper and pencils.
        %p
          &#187; $50 will help purchase a printer/scanner for a classroom, library, or computer lab.
        %p
          &#187; $100 can sponsor 4 different classrooms with School-Pak's or could purchase a classroom set of cd
          players with books on cd for reading and listening centers.
        %p
          &#187; $250 will help provide a computer for the media center or individual classroom along with
          appropriate software.
        %p
          &#187; $500 will help purchase interactive touch screen technology
      %p
        %strong
          Beyond an investment in our youth’s future, a donation to Tomorrow's Future Foundation can
          also be a financial benefit approaching tax time.
      %p
        %strong
          Contact an accountant to ensure you get the maximum benefit from your generous donation:
      %ol{:style => 'padding-left:30px;'}
        %li
          As a nonprofit corporation,
          = link_to "Tomorrow's Future Foundation", 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
          is classified by the Internal Revenue
          Service as exempt under IRS Section 501(c)3 and as a public charity under IRS Section 509.
          %br
          %br
        %li
          Keep records of your donations, including important, receipts or letters from
          = link_to "Tomorrow's Future Foundation", 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
          acknowledging receipt of your donation.
          %br
          %br
        %li
          Donations of more than $250 must be supported by record of payment from your bank.
          (Cancelled check, bank statement, etc.)
          %br
          %br
        %li
          Generally, no more than 50 percent of your adjusted gross income can be deducted. If you
          donate more, carry that non-deductible amount over into the next year.
      %p
        %strong Private Foundations
        %br
        As a public charity,
        = link_to "Tomorrow's Future Foundation", 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
        is qualified to receive grants from private foundations. A grant to
        = link_to "Tomorrow's Future Foundation", 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
        will help your foundation satisfy its annual distribution requirements while helping
        = link_to "Tomorrow's Future Foundation", 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
        accomplish its mission of serving children.
      %p
        %strong Donations of Securities
        %br
        In addition to donating cash to
        = link_to "Tomorrow's Future Foundation,", 'http://www.tomorrowsfuturefoundation.org', :target => '_blank'
        individual donors may make gifts of publicly traded securities. The donor is not taxed
        on any gain in the property, and the donor may deduct the fair market value of the
        gifted securities against other income (subject to certain limitations).
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_3kids.png", :width => "1000"}/

app/views/pages/faq.haml
- title 'Piece of the Future => FAQ'
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_purp.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_06.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_title_faqs.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "890"}
        %tr
          %td{:align => "left", :valign => "top"}
            %img{:height => "31", :src => "/images/thecontent_faqs_01.png", :width => "407"}/
          %td{:align => "right", :rowspan => "12", :valign => "top", :width => "280"}
            %img{:height => "400", :src => "/images/sidebanners_faqs.png", :width => "270"}/
        %tr
          %td{:align => "left", :style => "padding-left: 52px;", :valign => "top"}
            Its simple, we are trying to raise money for education.  All   proceeds will be      used to fund hundreds of schools, supply thousands   of teachers with resources,      and provide millions of students with   educational opportunities.
            %br/
        %tr
          %td{:align => "left", :valign => "top"}
            %br/
            %img{:height => "31", :src => "/images/thecontent_faqs_02.png", :width => "407"}/
        %tr
          %td{:align => "left", :style => "padding-left: 52px;", :valign => "top"} Tomorrow's Future Foundation is a 501(c)(3) non-profit      organization   that relies on our annual operating income from the generosity of        individuals and corporate donors whom have taken a vested interest in   our      youths educational process.
        %tr
          %td{:align => "left", :valign => "top"}
            %br/
            %img{:height => "31", :src => "/images/thecontent_faqs_03.png", :width => "407"}/
        %tr
          %td{:align => "left", :style => "padding-left: 52px;", :valign => "top"}
            In an effort to raise awareness and funds, we are selling 200,000 boxes for $5 per box. The motivation for doing this is to SUPPORT   EDUCATION.            Everyone is welcome to become part of the future   and donate to receive a box,      which are available for $5.
            %br/
            = succeed "You" do
              %br/
            can buy as many boxes as you like, as long as there are boxes available (see the live stats in the top right corner of the page). When you buy a box, you can then display an image/ad/logo of your choice in the space you have purchased. You can also have the image click through to your own website. However, no obscene or offensive images are allowed and will not be posted.
            %br/
            = succeed "The" do
              %br/
            boxes you buy will be displayed on the homepage permanently as you sign up to renew annually. The homepage will not change. Tomorrows Future Foundation wants it to become a kind of Educational Internet time capsule. So, in the long run, the boxes will offer good value and raise very needed funds. You will be part piece of Educational Internet history!
            %br/
            %br/
            Our organization operates by locating and filling educational voids found throughout school systems by supplying schools and classrooms with tools and resources. It is our belief that in order for our youth to be successful in tomorrow's world, students must become prepared today. The Foundation's contributions to the classrooms are in an effort to make for a better established tomorrow.
        %tr
          %td{:align => "left", :valign => "top"}
            %br/
            %img{:height => "31", :src => "/images/thecontent_faqs_04.png", :width => "407"}/
        %tr
          %td{:align => "left", :style => "padding-left: 52px;", :valign => "top"}
            All uploaded images must be in
            %a{:href => "http://en.wikipedia.org/wiki/Portable_Network_Graphics"} PNG
            ,
            %a{:href => "http://en.wikipedia.org/wiki/Jpg"} JPG
            ,or
            %a{:href => "http://en.wikipedia.org/wiki/Gif"} GIF
            format.
        %tr
          %td{:align => "left", :valign => "top"}
            %br/
            %img{:height => "31", :src => "/images/thecontent_faqs_05.png", :width => "407"}/
        %tr
          %td{:align => "left", :style => "padding-left: 52px;", :valign => "top"}
            You will have the opportunity to win 513
            = link_to 'prizes', prizes_path
            totaling $500,000
            %br/
            %br/
            You will also have an image and a link to your site on the homepage of a site that could potentially be seen by millions of people over the coming years.
        %tr
          %td{:align => "left", :valign => "top"}
            %br/
            %img{:height => "31", :src => "/images/thecontent_faqs_06.png", :width => "407"}/
        %tr
          %td{:align => "left", :style => "padding-left: 52px;", :valign => "top"} You can upload any image of your choosing from logos to pictures, so   long as      your upload does not contain inappropriate or obscene   images or links.
        %tr
          %td{:align => 'left', :valign => 'top'}
            %br
            = image_tag 'thecontent_faqs_07.png', :size => '407x31'
        %tr
          %td{:align => "left", :style => "padding-left:52px;", :valign => "top"}
            Your generosity provides the funds to acquire those wish list                    items, increasing the success rates of our youths.
            %br
            %br
            %blockquote{:style => 'padding-left:30px;'}
              %p » $20 Supplies 145students with paper, pencils, and erasers.
              %p
                » $25Buys a School-Psk which includes:
                %br/
                %br/
                1 box crayons(24ct), erasers, 2pocketed folders, 140z glue, ruler, scissors,
                %br/
                1                      set washable markers, 4 - 70pg notebooks, pencils, 1set colored                      pencils, paper and pencils.
              %p » $50 will help purchases a printer/scanner for a classroom, library, or                      computer lab.
              %p » $100 can sponsor 4 different classrooms with School-Pak's. Or could                      purchase a classroom set of cd players w/ books on cd for reading and                      listening centers.
              %p » $250 will help provide a computer for the media center or individual                      classroom along with appropriate software.
              %p » $500 will help purchase interactive touch screen technology.

        %tr
          %td{:align => "left", :valign => 'top'}
            %br
            = image_tag 'thecontent_faqs_08.png', :size => '407x31'
        %tr
          %td{:align => "left", :style => "padding-left:52px;", :valign => "top"}
            No one can deny that the public school systems in Florida are in dire                      financial straits because of the budgetary cuts. Counties throughout Florida are continuously being asked to tighten their belts. That equates to a decrease in funding of $1000 per student next year, and a sharp decrease in necessary supplies for schools, teachers, and ultimately the students.
            %br
            %br
            Funding is important to the success of the public school system,                      academic achievement, and the retention of quality educators. Educators are the driving force of the school system and are constantly being asked to do more with less.
            %br
            %br
            %blockquote{:style => 'padding-left:30px;'}
              %p » Your donation provides a school with materials, teachers with                      resources. and students with the opportunity to succeed.
              %p » It promotes your company, as a business with an investment in                      the future and lasting ties to the community.
              %p
                » Your generosity creates a better educated community. which                      translates into smarter employees and consumers.

- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_woman.png", :width => "1000"}/

app/views/pages/prizes.haml
- title 'Piece of the Future => Prizes'
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_lightblue.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_03.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_title_prizes.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "890"}
        %tr
          %td{:align => "left", :style => "padding: 20px;", :valign => "top"} Every donor’s generosity will greatly impact the lives of so    many.   Upon donating you will receive your very own Piece of the  Future,   as   well as, the opportunity to register an educational  institution,     school, classroom, or teacher to receive a donation  on your behalf.      Educational institutions, schools, classrooms,  and teachers will be     randomly selected to receive a donation using  a lottery style drawing.      Registered recipients may receive one of  the more than  500      giveaways.
        %tr
          %td{:align => "left", :valign => "top"}
            %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "890"}
              %tr
                %td{:align => "center", :valign => "top", :width => "148"}
                  %img{:height => "240", :src => "/images/prizes_1card.png", :width => "140"}/
                %td{:align => "center", :valign => "top", :width => "148"}
                  %img{:height => "240", :src => "/images/prizes_1.png", :width => "140"}/
                %td{:align => "center", :valign => "top", :width => "148"}
                  %img{:height => "240", :src => "/images/prizes_10.png", :width => "140"}/
                %td{:align => "center", :valign => "top", :width => "148"}
                  %img{:height => "240", :src => "/images/prizes_50.png", :width => "140"}/
                %td{:align => "center", :valign => "top", :width => "148"}
                  %img{:height => "240", :src => "/images/prizes_200.png", :width => "140"}/
                %td{:align => "center", :valign => "top", :width => "150"}
                  %img{:height => "240", :src => "/images/prizes_250.png", :width => "140"}/
              %tr
                %td{:align => "center", :colspan => "6", :valign => "top"}
                  %img{:height => "240", :src => "/images/ipadraffle.png", :width => "600"}/
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_teacher.png", :width => "1000"}/

app/views/pages/terms.haml
- title 'Piece of the Future => Buy-A-Box'
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:align => "left", :style => "background: url('/images/thecontent_quotebg_green.png') no-repeat; height: 155px;", :valign => "top"}
      %img{:height => "155", :src => "/images/thecontent_quote_02.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"} &nbsp;
  %tr
    %td{:align => "left", :valign => "top"}
      %img{:height => "64", :src => "/images/thecontent_subtitle_terms.png", :width => "890"}/
  %tr
    %td{:align => "left", :valign => "top"}
      %div
        %dl
        %h3 Submission Rules
        %dd The minimum donation is $5 (1 box), and the maximum donation is the  remaining amount of boxes.
        %dd When donating for boxes you will not have any ownership rights to   any  part of the homepage or this site, but will be granted the right to    submit an image and link which will then be published on the homepage    in the respective space you have paid for.
        %dd You cannot change the image or link once you have submitted them,   so  you must be sure of the image &amp; link you want on the homepage,   which  will be there for at least 10 years.
        %dd If your image and link are accepted and published on the homepage,  you will not receive a refund.
        %dd Tomorrows Future Foundation guarantees your picture will remain    online as long as you continue to donate to the Piece of the Future   cause.
        %dd No obscene/offensive/adult images/links will be accepted, and   Tomorrows  Future Foundation will decide what is appropriate for the   site. If you  submit an image or link that is rejected, you will have   the opportunity  to provide an alternative, otherwise your money will be   refunded and you  will lose your boxes.
        %dd If for whatever reason in the future you want your image and link    removed from the homepage, you can do that, but you will not get a    refund and the space will become publicly available again.
        %dd
          All uploaded images must be in
          %a{:href => "http://en.wikipedia.org/wiki/Portable_Network_Graphics"} PNG
          ,
          %a{:href => "http://en.wikipedia.org/wiki/Jpg"} JPG
          ,or
          %a{:href => "http://en.wikipedia.org/wiki/Gif"} GIF
          format.
        %dd Images must NOT be animated.
        %dd Links must be to web pages only and begin with http://
        %dd You must have the authority to provide the image and link for the website  you submit.
        %dd Funds must be fully received and cleared before your boxes go live on the homepage.
        %dd There might be occasional downtime for site maintenance.
        %dd Once you have ordered and the funds have cleared your box will be published within  72 hours.
        %dl
          %dt
            %h3 Limited Time Give Away:
        %dd For a Limited amount of time (until August10th 2011), you will receive a iPad raffle  ticket for each box purchased.
        %dl
          %dt
            %h3 Final Drawing for Boxes
        %dd The Final drawing for the giveaways will be done in a lottery   type drawing  with tumbler type device. Anyone who wishes to be present   at the actual  drawing may do so.
        %dd The drawing will be held in Jacksonville Florida when and only   when all  200,000 boxes on the site are purchased. The drawing will be   held within  60 days after the final box is purchased.
        %dd Location of drawing will be determined no later than 10 days after the  last box is sold.
        %dd The winner of this fundraiser need not be present to win.
        %dd Any business or person whose box number is selected at the final    drawing will receive their prize or prizes and educational will    receive there donation or donations from Tomorrows Future Foundation  on   the winners behalf.
        %dd Prize will be paid in full no longer than 30 days after final drawing.
      %div{:style => 'margin:0 auto;width:800px;padding-top:20px;text-align:center;'}
        %p
          ** Please note that your donation to
          = link_to 'www.pieceofthefuture.org', root_url
          will automatically be
          renewed by PayPal services annually.  If you wish for this donation to be a one-time donation
          and do not wish to have your donation auto-renewed, please send an email or
          = link_to 'contact us', contact_path
          if you would like this removed. **
        = link_to 'Agree', new_donation_path, :class => 'styled_button blue', :style => 'color:white;'
.clear
- content_for :bannerimg do
  %img{:height => "258", :src => "/images/bannerimg_teacher.png", :width => "1000"}/