config/routes.rb
Pieceofthefuture::Application.routes.draw do      
  devise_for :users
  get '/institutions/search' => 'institutions#search'
  post '/institutions/get_institution'
  post '/classrooms/get_classroom'
  resources :institutions
  resources :classrooms

  match '/donations/receipt/:id' => 'donations#receipt', :as => :receipt
  match '/donations/send_information/:id' => 'donations#send_information', :as => :send_information
  match 'donations/update_classroom_select/:id' => 'donations#update_classroom_select'
  resources :donations
  post '/donate/send_email'
  match 'faq' => 'high_voltage/pages#show', :id => 'faq'
  match 'about_tff' => 'high_voltage/pages#show', :id => 'about_tff'
  match 'terms_and_conditions' => 'high_voltage/pages#show', :id => 'terms'
  match 'prizes' => 'high_voltage/pages#show', :id => 'prizes'
  match 'contributors' => 'contributors#index'
  match 'contact' => 'contact_mailer#index'
  post 'contact_mailer/send_email'

  root :to => 'home#index'

end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.haml
#footerarea
  %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "1000"}
    %tr
      %td{:align => "left", :valign => "bottom", :width => "707"}
        #footer_left
          = link_to image_tag('composedpixels.png', :alt => 'ComposedPixels', :id => 'composedpixels'), 'https://composedpixels.com', :target => '_blank'
          = link_to image_tag('evanmachnic.png', :alt => 'Evan Machnic', :id => 'evanmachnic'), 'https://broadmac.net', :target => '_blank'
      %td{:align => "right", :valign => "bottom", :width => "293"}
        %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "261"}
          %tr
            %td{:align => "left", :colspan => "5", :valign => "top"}
              %img{:alt => "", :height => "22", :src => "/images/footer_followus.png", :width => "261"}/
          %tr
            %td{:align => "left", :valign => "top", :width => "98"}
              %img{:alt => "", :height => "29", :src => "/images/footer_followarrow.png", :width => "98"}/
            %td{:align => "left", :valign => "top", :width => "49"}
              %a#footer_facebook{:href => "https://www.facebook.com/pages/Tomorrows-Future-Foundation/127003594039657?sk=wall", :target => "_blank"}
            %td{:align => "left", :valign => "top", :width => "49"}
              %a#footer_twitter{:href => "https://twitter.com/tffoundation", :target => "_blank"}
            %td{:align => "left", :valign => "top", :width => "49"}
              %a#footer_myspace{:href => "https://www.myspace.com/tomorrowsfuturefoundation", :target => "_blank"}
            %td{:align => "left", :valign => "top", :width => "16"}
              %a{:href => "https://www.myspace.com/tomorrowsfuturefoundation", :onmouseout => "MM_swapImgRestore()", :onmouseover => "MM_swapImage('footer_myspace','','/images/footer_myspace_on.png',1)", :target => "_blank"}
                %img{:alt => "", :border => "0", :height => "29", :src => "/images/footer_09.png", :width => "16"}/
          %tr
            %td{:align => "left", :colspan => "5", :valign => "top"} &nbsp;
#footer_copyright
  %a{:href => 'https://www.tomorrowsfuturefoundation.org'}
    %img{:alt => "", :height => "34", :src => "/images/footer_copyright.png", :width => "261"}/

app/views/layouts/_header.haml
#header
  - flash.each do |flash_type, message|
    = content_tag :div, message, :class => "flash #{flash_type} home"
  #kids{:style => 'float:left;'}
    = image_tag 'header_kids.png', :alt => 'Kids holding puzzle pieces'
  #logo{:style => 'float:right;'}
    = link_to image_tag('header_logo.png', :alt => 'Piece of the Future logo', :style => 'border:none;', :id => 'header_logo'), root_url, :style => 'border:none;'
    %p#brought_by
      BROUGHT TO YOU BY
      %strong= link_to "TOMORROW'S FUTURE FOUNDATION", 'https://www.tomorrowsfuturefoundation.org', :target => '_blank'
      and
      %strong CORPORATE SPONSOR
  .clear

app/views/layouts/_menu_items.html.erb
<div id='menu' class='clear'>
  <ul>
    <li><%= link_to '', root_url, :id => 'home', :class => if_active_controller?('home') %></li>
    <li class='splitter'><%= image_tag 'tff_navi_splitter.png', :alt => 'Splitter' %></li>
    <li><%= link_to '', about_tff_path, :id => 'about', :class => active_if?('about_tff')%></li>
    <li class='splitter'><%= image_tag 'tff_navi_splitter.png', :alt => 'Splitter' %></li>
    <li><%= link_to '', donations_path, :id => 'buyabox', :class => if_active_controller?('donations') || active_if?('terms') %></li>
    <li class='splitter'><%= image_tag 'tff_navi_splitter.png', :alt => 'Splitter' %></li>
    <li><%= link_to '', prizes_path, :id => 'prizes', :class => active_if?('prizes') %></li>
    <li class='splitter'><%= image_tag 'tff_navi_splitter.png', :alt => 'Splitter' %></li>
    <li><%= link_to '', institutions_path, :id => 'classrooms', :class => if_active_controller?('institutions') || if_active_controller?('classrooms') %></li>
    <li class='splitter'><%= image_tag 'tff_navi_splitter.png', :alt => 'Splitter' %></li>
    <li><%= link_to '', contributors_path, :id => 'contributors', :class => if_active_controller?('contributors') %></li>
    <li class='splitter'><%= image_tag 'tff_navi_splitter.png', :alt => 'Splitter' %></li>
    <li><%= link_to '', faq_path, :id => 'faq', :class => active_if?('faq') %></li>
    <li class='splitter'><%= image_tag 'tff_navi_splitter.png', :alt => 'Splitter' %></li>
    <li><%= link_to '', contact_path, :id => 'contact_nav', :class => if_active_controller?('contact_mailer') %></li>
  </ul>
</div>

app/views/layouts/_top_bar.haml
#top
  #insidetop
    .top_1
      .top_2
        .top_3
          %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :style => "height: 38px;", :width => "100%"}
            %tr{:valign => "middle"}
              %td{:width => "183"}
                %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "176"}
                  %tr
                    %td{:width => "69"}
                      %img{:height => "31", :src => "/images/sitemeter_left.png", :width => "74"}/
                    %td{:align => "center", :style => "background: url('/images/sitemeter_mid.png') repeat-x; font-size: 11px; color: #ccc;", :width => "98"}
                      %a{:title => "web stats", :href => "https://statcounter.com/", :target => "_blank", :style => 'border:none;'}
                        %img{:class => "statcounter", :src => "https://c.statcounter.com/6763400/0/dace8399/0/", :alt => "web stats", :style => 'border:none;'}
                    %td{:width => "16"}
                      %img{:height => "31", :src => "/images/sitemeter_right.png", :width => "18"}/
              %td#top_social{:width => "116"}
                %a#topfacebook{:href => "https://www.facebook.com/pages/Tomorrows-Future-Foundation/127003594039657?sk=wall", :target => "_blank", :alt => 'Facebook Link'}
                %a#toptwitter{:href => "https://twitter.com/tffoundation", :target => "_blank", :alt => 'Twitter Link'}
                %a#topmyspace{:href => "https://www.myspace.com/tomorrowsfuturefoundation", :target => "_blank", :alt => 'MySpace Link'}
              %td{:width => "199"}
                %span{:style => "font-size: 11px; color: #444; font-weight: bold;"}= Time.now.strftime("%B %d, %Y")
              %td{:width => "69"}
                %img{:alt => "", :height => "38", :src => "/images/date_spacer.png", :width => "9"}/
              %td{:width => "214"}
                %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "200"}
                  %tr
                    %td{:width => "96"}
                      %img{:height => "31", :src => "/images/reservedboxes_left.png", :width => "96"}/
                    %td{:align => "center", :style => "background: url('/images/reservedboxes_mid.png') repeat-x; color: #630;vertical-align:top;padding-top:8px;", :width => "86"}
                      - if Box.first
                        = 200000 - Box.first.quantity
                    %td{:width => "18"}
                      %img{:height => "31", :src => "/images/reservedboxes_right.png", :width => "18"}/
              %td{:width => "200"}
                %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "200"}
                  %tr
                    %td{:width => "96"}
                      %img{:alt => "", :height => "31", :src => "/images/availboxes_left.png", :width => "96"}/
                    %td{:align => "center", :style => "background: url('/images/availboxes_mid.png') repeat-x; color: #F9D632;vertical-align:top;padding-top:8px;", :width => "86"}
                      - if Box.first
                        = Box.first.quantity
                    %td{:width => "18"}
                      %img{:alt => "", :height => "31", :src => "/images/availboxes_right.png", :width => "18"}/

app/views/layouts/application.haml
!!!
%html{:xmlns => "https://www.w3.org/1999/xhtml", "xmlns:og" => "https://opengraphprotocol.org/schema/", "xmlns:fb" => "https://www.facebook.com/2008/fbml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %title= yield(:title) || "Piece of the Future"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    /%meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1.0' }
    %meta{:property => "og:title", :content => 'I bought a Piece of the Future'}/
    %meta{:property => "og:url", :content => "https://www.pieceofthefuture.org"}
    %meta{:property => "og:image", :content => "https://www.pieceofthefuture.org/images/header_logo.png"}
    %meta{:property => "og:description", :content => "Please join Tomorrow's Future Foundation in a show of Support for Education. As we raise awareness and funds for our children in an effort to establish a better tomorrow."}
    = stylesheet_link_tag 'application', :cache => true
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'
    = javascript_include_tag 'rails', 'application'
    /= javascript_include_tag 'green_light'
    /[if lt IE 9]
      = javascript_include_tag 'https://html5shiv.googlecode.com/svn/trunk/html5.js'
    /[if IE 7]
      = stylesheet_link_tag 'ie'
    = javascript_include_tag "https://connect.facebook.net/en_US/all.js#xfbml=1"
    = csrf_meta_tag
    = yield(:head)
  %body
    = render 'layouts/top_bar'
    = render 'layouts/header'
    = render 'layouts/menu_items'
    #contentwrapper
      .content_full
        .box_t1
          .box_t2
            .box_t3
        .box_1
          .box_2
            .box_3
              = yield 
        .box_b1
          .box_b2
            .box_b3
      .clear
    #bannerimg
      = yield(:bannerimg)
    = render 'layouts/footer'
    = yield(:bottom_scripts)

app/views/layouts/home.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %title= yield(:title) || "Piece of the Future"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    %meta{:property => "og:title", :content => 'I bought a Piece of the Future'}
    %meta{:property => "og:url", :content => "http://pieceofthefuture.org"}
    %meta{:property => "og:image", :content => "http://pieceofthefuture.org/images/header_logo.png"}
    %meta{:property => "og:description", :content => "Please join Tomorrow's Future Foundation in a show of Support for Education. As we raise awareness and funds for our children in an effort to establish a better tomorrow."}
    /%meta{ :name => 'viewport', :content => 'width=1024, initial-scale=1.0' }
    = stylesheet_link_tag 'application', :cache => true
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'
    = javascript_include_tag 'application'
    /[if lt IE 9]
      = javascript_include_tag 'http://html5shiv.googlecode.com/svn/trunk/html5.js'
    /[if IE 7]
      = stylesheet_link_tag 'ie'
    = csrf_meta_tag
    = yield(:head)
  %body
    = render 'layouts/top_bar'
    = render 'layouts/header'
    .chalk_t1.clear
      .chalk_t2
        .chalk_t3
    .chalk_1
      .chalk_2
        .chalk_3
          = render 'layouts/menu_items'
          #pixelwrapper
            = yield
    .chalk_b1
      .chalk_b2
        .chalk_b3
    #bannerimg
      = yield(:bannerimg)
    = render 'layouts/footer'
    = javascript_include_tag 'http://cdn.jquerytools.org/1.2.5/all/jquery.tools.min.js'
    = javascript_include_tag 'tooltip'